# Generated by Django 3.1.2 on 2020-11-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ala', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True)),
                ('idade', models.TextField(unique=True)),
                ('convenio', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leito', models.TextField(unique=True)),
                ('ala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ala', to='internacao.ala')),
            ],
        ),
        migrations.CreateModel(
            name='Ineternacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.TextField(unique=True)),
                ('dieta', models.TextField(unique=True)),
                ('situacao', models.TextField(unique=True)),
                ('observacao', models.TextField(unique=True)),
                ('entrada', models.DateTimeField()),
                ('cor', models.TextField(blank=True)),
                ('paciente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internacao.paciente')),
            ],
        ),
    ]
