# Generated by Django 3.1.2 on 2020-11-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.TextField(blank=True, null=True)),
                ('dieta', models.TextField(blank=True, null=True)),
                ('situacao', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('entrada', models.DateTimeField()),
                ('alta', models.TextField(blank=True, null=True)),
                ('cor', models.TextField(blank=True)),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Leito', to='internacao.leito')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Ineternacao',
        ),
        migrations.AddField(
            model_name='internacao',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internacao.paciente'),
        ),
    ]
