# Generated by Django 3.1.2 on 2020-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0003_auto_20201130_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leito',
            name='ala',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AlterField(
            model_name='internacao_painel',
            name='ala',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Ala',
        ),
        migrations.DeleteModel(
            name='Leito',
        ),
    ]
