# Generated by Django 3.1.2 on 2020-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0004_auto_20201130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacao_painel',
            name='leito',
            field=models.TextField(),
        ),
    ]
