# Generated by Django 3.1.2 on 2020-12-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0006_auto_20201202_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internacao_painel',
            options={'ordering': ['ala', 'leito']},
        ),
    ]
