# Generated by Django 3.1.2 on 2021-02-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0007_auto_20201223_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao_SAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exames', models.TextField(blank=True, null=True)),
                ('outros', models.TextField(blank=True, null=True)),
                ('alta', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internacao.internacao_painel')),
            ],
        ),
    ]
