# Generated by Django 3.1.2 on 2021-06-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0008_internacao_sae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao_Painel_Tasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codat', models.TextField(blank=True, null=True, unique=True)),
                ('leito', models.TextField(blank=True, null=True)),
                ('codpac', models.TextField(blank=True, null=True)),
                ('convenio', models.IntegerField(blank=True, null=True)),
                ('medico', models.TextField(blank=True, null=True)),
                ('paciente', models.TextField(blank=True, null=True)),
                ('proce', models.TextField(blank=True, null=True)),
                ('alta', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
