# Generated by Django 3.1.2 on 2021-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0009_internacao_painel_tasy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internacao_painel_tasy',
            options={'ordering': ['codat']},
        ),
        migrations.AlterField(
            model_name='internacao_painel_tasy',
            name='codat',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
