# Generated by Django 3.1.2 on 2021-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0010_auto_20210618_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internacao_painel_tasy',
            options={},
        ),
        migrations.RemoveField(
            model_name='internacao_painel_tasy',
            name='codat',
        ),
        migrations.AlterField(
            model_name='internacao_painel_tasy',
            name='alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacao_painel_tasy',
            name='leito',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
