# Generated by Django 3.1.2 on 2021-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0011_auto_20210618_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacao_painel_tasy',
            name='entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
