# Generated by Django 3.1.2 on 2021-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0013_auto_20210618_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentosPaMedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.TextField(blank=True, null=True)),
                ('procedimento', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
