# Generated by Django 3.1.2 on 2021-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0014_procedimentospamedicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soro_Painel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('leito', models.TextField()),
                ('ala', models.TextField()),
                ('situacao', models.TextField(blank=True, null=True)),
                ('entrada', models.DateTimeField()),
                ('alta', models.DateTimeField()),
                ('cor', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ala', 'leito'],
            },
        ),
    ]
