# Generated by Django 3.1.2 on 2020-11-04 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='questionario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ouvidoria.questionario'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ouvidoria.pergunta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ouvidoria.resposta'),
        ),
    ]
