# Generated by Django 3.0.6 on 2020-06-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
    ]
