# Generated by Django 3.0.6 on 2020-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_senha_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='guiche',
            field=models.TextField(blank=True, null=True),
        ),
    ]
