# Generated by Django 3.0.6 on 2020-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_senha_guiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='preferencial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
