# Generated by Django 3.0.6 on 2020-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_senha_preferencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeraSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.IntegerField()),
            ],
        ),
    ]
