# Generated by Django 3.0.8 on 2020-07-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_dadostriagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadostriagem',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
