# Generated by Django 3.0.8 on 2020-07-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_dadostriagem_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guiche', models.TextField(blank=True, null=True)),
                ('atendente', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dadostriagem',
            name='dataCham',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senha',
            name='dataCham',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senha',
            name='dataImp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gerasenha',
            name='senha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senha',
            name='senha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senha',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AtendimentoGuiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAten', models.DateTimeField()),
                ('guiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='painel.Guiche')),
                ('senha', models.ManyToManyField(to='painel.Senha')),
            ],
        ),
    ]
