# Generated by Django 3.0.8 on 2020-07-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_auto_20200723_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiche',
            name='atendente',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guiche',
            name='guiche',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
