# Generated by Django 3.0.8 on 2020-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_consulta_consultorio_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='medico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
