# Generated by Django 3.0.8 on 2020-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_auto_20200724_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dataCham',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
