# Generated by Django 3.1.2 on 2021-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0013_triagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadostriagem',
            options={'ordering': ['senha']},
        ),
        migrations.AlterModelOptions(
            name='senha',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='guiche',
            name='guiche',
            field=models.TextField(blank=True, null=True),
        ),
    ]
