# Generated by Django 3.0.6 on 2020-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_InfoHosp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('nascimento', models.TextField()),
                ('cpf', models.TextField()),
                ('rua', models.TextField()),
                ('bairro', models.TextField()),
                ('numero', models.TextField()),
                ('complemento', models.TextField()),
                ('cidade', models.TextField()),
                ('CEP', models.TextField()),
                ('medico', models.BooleanField()),
                ('crm_tipo', models.TextField()),
                ('crm_numero', models.TextField()),
                ('crm_espec', models.TextField()),
                ('consultorio', models.BooleanField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dados_pessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('nome', models.TextField()),
                ('setor', models.TextField()),
                ('cargo', models.TextField()),
                ('telefone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('status', models.TextField()),
                ('mensagem', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_ti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.TextField()),
                ('user', models.IntegerField()),
                ('setor', models.TextField()),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('atendente', models.TextField(blank=True, null=True)),
                ('data_solcitada', models.TextField()),
                ('data_concluida', models.TextField(blank=True, null=True)),
                ('status_ordem', models.TextField()),
                ('descricao', models.TextField()),
                ('tempo_atendimento', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
