# Generated by Django 3.0.6 on 2020-05-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200517_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem_ti',
            name='materiais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordem_ti',
            name='servico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
