# Generated by Django 3.0.6 on 2020-05-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200517_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_Manu_arCond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.TextField()),
                ('user', models.IntegerField()),
                ('setor', models.TextField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('atendente', models.TextField(blank=True, null=True)),
                ('data_solcitada', models.TextField()),
                ('data_concluida', models.TextField(blank=True, null=True)),
                ('status_ordem', models.TextField()),
                ('descricao', models.TextField()),
                ('tempo_atendimento', models.TextField(blank=True, null=True)),
                ('laudos', models.TextField(blank=True, null=True)),
                ('servico', models.TextField(blank=True, null=True)),
                ('materiais', models.TextField(blank=True, null=True)),
                ('prioridade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_Manu_predial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.TextField()),
                ('user', models.IntegerField()),
                ('setor', models.TextField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('atendente', models.TextField(blank=True, null=True)),
                ('data_solcitada', models.TextField()),
                ('data_concluida', models.TextField(blank=True, null=True)),
                ('status_ordem', models.TextField()),
                ('descricao', models.TextField()),
                ('tempo_atendimento', models.TextField(blank=True, null=True)),
                ('laudos', models.TextField(blank=True, null=True)),
                ('servico', models.TextField(blank=True, null=True)),
                ('materiais', models.TextField(blank=True, null=True)),
                ('prioridade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_Manu_terceiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.TextField()),
                ('user', models.IntegerField()),
                ('setor', models.TextField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('atendente', models.TextField(blank=True, null=True)),
                ('data_solcitada', models.TextField()),
                ('data_concluida', models.TextField(blank=True, null=True)),
                ('status_ordem', models.TextField()),
                ('descricao', models.TextField()),
                ('tempo_atendimento', models.TextField(blank=True, null=True)),
                ('laudos', models.TextField(blank=True, null=True)),
                ('servico', models.TextField(blank=True, null=True)),
                ('materiais', models.TextField(blank=True, null=True)),
                ('prioridade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro_infohosp',
            name='user',
        ),
        migrations.AddField(
            model_name='cadastro_infohosp',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ordem_ti'),
        ),
    ]
