# Generated by Django 3.0.6 on 2020-06-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200521_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacoes',
            name='contato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
