# Generated by Django 3.0.6 on 2020-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_compra_estoque_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='depatarmento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='CEP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='bairro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='cidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='complemento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='crm_espec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='crm_numero',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='crm_tipo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='numero',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_infohosp',
            name='rua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
