# Generated by Django 3.0.6 on 2020-06-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200609_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagens',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
