# Generated by Django 3.1.2 on 2021-06-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200714_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordem_manu_arcond',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ordem_manu_predial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ordem_manu_terceiri',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ordem_ti',
            options={'ordering': ['id']},
        ),
    ]
