from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name ='index'),
    path('cadastrar_usuario', views.cadastrar_usuario, name="cadastrar_usuario"),
    path('logar_usuario', views.logar_usuario, name="logar_usuario"),
    path('logout', views.logout, name="logout"),
    path('dadospessoais', views.dadospessoais, name="dadospessoais"),
    path('gordti', views.gerar_ordemti, name="gerar_ordemti"),
    path('gordmanu', views.gerar_ordemManu, name="gerar_ordemManu"),
    path('ordemti_a', views.ordemti_a, name="ordemti_a"),
    path('ordemManu_a', views.ordemManu_a, name="ordemManu_a"),
    path('ordemti_f', views.ordemti_f, name="ordemti_f"),
    path('ordemManu_f', views.ordemManu_f, name="ordemManu_f"),
    path('ordemti_cro', views.ordemti_cro, name="ordemti_cro"),
    path('ordemManu_cro', views.ordemManu_cro, name="ordemManu_cro"),
    path('ordemti_ini/<int:id>', views.ordemti_ini, name="ordemti_ini"),
    path('ordemManu_ini/<int:id>/<str:tipo>', views.ordemManu_ini, name="ordemManu_ini"),
    path('ordemti_paus/<int:id>', views.ordemti_paus, name="ordemti_paus"),
    path('ordemManu_paus/<int:id>/<str:tipo>', views.ordemManu_paus, name="ordemManu_paus"),
    path('ordemti_edit/<int:id>/', views.ordemti_edit, name="ordemti_edit"),
    path('ordemManu_edit/<int:id>/<str:tipo>', views.ordemManu_edit, name="ordemManu_edit"),
    path('ordemti_fim/<int:id>', views.ordemti_fim, name="ordemti_fim"),
    path('ordemManu_fim/<int:id>/<str:tipo>', views.ordemManu_fim, name="ordemManu_fim"),
    path('vis_ordemti/<int:id>', views.vis_ordemti, name='vis_ordemti'),
    path('vis_ordemManu/<int:id>/<str:tipo>', views.vis_ordemManu, name='vis_ordemManu'),
    path('del_ordemti/<int:id>', views.del_ordemti, name='del_ordemti'),
    path('del_ordemManu/<int:id>/<str:tipo>', views.del_ordemManu, name='del_ordemManu'),
    path('edit_pri_ordemti/<int:id>', views.edit_pri_ordemti, name='edit_pri_ordemti'),
    path('edit_pri_ordemManu/<int:id>/<str:tipo>', views.edit_pri_ordemManu, name='edit_pri_ordemManu'),
    path('cadastro_infohosp', views.cadastro_infohosp, name='cadastro_infohosp'),
    path('cadastro_infohosp_vis/<int:id>', views.cadastro_infohosp_vis, name='cadastro_infohosp_vis'),
    path('estoque', views.estoque, name='estoque'),
    path('notifications', views.view_notifications, name='notifications'),
    path('del_notifications/<int:id>', views.del_notifications, name='del_notifications'),
    path('delt_notifications/<int:user>', views.delt_notifications, name='delt_notifications'),
    path('lida_notifications/<int:id>', views.lida_notifications, name='lida_notifications'),
    path('lidat_notifications/<int:user>', views.lidat_notifications, name='lidat_notifications'),
    path('cadastrarProdutos', views.cadastrarProdutos, name='cadastrarProdutos'),
    path('estoque/<str:departamento>', views.produtos, name='produtos'),
    path('produto_delete/<int:id>', views.produto_delete, name='produto_delete'),
    path('produto_update/<int:id>', views.produto_update, name='produto_update'),
    path('produto_add/<int:id>', views.produto_add, name='produto_add'),
    path('produto_addc/<int:id>/<int:ordem>', views.produto_addc, name='produto_addc'),
    path('prodImagem_add/<int:id>', views.prodImagem_add, name='prodImagem_add'),
    path('prodImagem_del/<int:id>/<int:produto>', views.prodImagem_del, name='prodImagem_del'),
    path('compra/<str:departamento>/<int:id>', views.compra, name='compra'),
]

